#!/usr/bin/env python3
"""The addresses this system can speak -- a view of the one truth.

**Why this is not the traffic window.** The window counts what flew past Core.
It cannot answer "what is the address for a channel's aux send", because an
address nobody has sent has no row there at all. A log shows what happened; a
register shows what is possible.

Until 2026-09-30 the register was lifted out of six places in four repos where
addresses were written, and its test had to rebuild it from the neighbouring
checkouts. Every address is written once now, in a3-osc.json, so the register
is a view of that file -- checked in as share/a3-core/osc-register.json,
because the installed Core reads a finished file, and held to the truth by
tools/tests/test_osc_register.py.

`direction` is from Core's side: `in` Core hears it, `out` Core says it
(itself, as a relay or as an announcement), `both` the two, and `aside` the
device's traffic that passes Core by. The words we speak but do not own --
REAPER's, the IEM plug-ins' -- are in the truth without a direction, and are
listed as `both`: the truth does not say more, and neither does this.
"""

import json
import sys
from pathlib import Path

PACKAGE = "platform-config/debian-x86_64/a3-core"
TRUTH = f"{PACKAGE}/usr/share/a3/a3-osc.json"
REGISTER = f"{PACKAGE}/home/aaa/.local/share/a3-core/osc-register.json"

DIRECTIONS = ("in", "out", "both", "aside")

COMMENT = ("Generated by tools/osc_register.py from a3-osc.json -- edit the "
           "truth and regenerate, never this file.")


def _entry(address, device, direction, source, note):
    return {"address": address, "device": device, "direction": direction,
            "source": source, "note": note}


def _ours(truth):
    """(address, device, direction, key, meaning) for every address of ours."""
    for key, entry in truth.addresses().items():
        senders = [p for p in entry.get("from", [])]
        receivers = [p for p in entry.get("to", [])]
        told_by_core = entry.get("relayed_to", []) + entry.get("announced_to", [])
        for sender in senders:
            if sender != "core" and "core" in receivers:
                yield entry["pattern"], sender, "in", key, entry["meaning"]
        for receiver in (receivers if "core" in senders else []) + told_by_core:
            if receiver != "core":
                yield entry["pattern"], receiver, "out", key, entry["meaning"]
        for sender in senders:
            for receiver in receivers:
                if "core" not in (sender, receiver) and sender != receiver:
                    yield entry["pattern"], receiver, "aside", key, entry["meaning"]


def _merged(rows):
    """One row per (address, device): `in` and `out` together are `both`."""
    seen = {}
    for address, device, direction, key, meaning in rows:
        before = seen.get((address, device))
        if before is None:
            seen[(address, device)] = [direction, key, meaning]
        elif before[0] != direction and {before[0], direction} <= {"in", "out", "both"}:
            before[0] = "both"
    return [_entry(address, device, direction, f"a3-osc.json: {key}", meaning)
            for (address, device), (direction, key, meaning) in sorted(seen.items())]


def build(truth):
    """The whole register, from the truth. Nothing dated or counted: the test
    compares it byte for byte against the checked-in file."""
    entries = _merged(_ours(truth))
    for owner, block in sorted(truth.external().items()):
        for pattern in block["patterns"]:
            entries.append(_entry(pattern, owner, "both",
                                  f"a3-osc.json: external.{owner}", block["owner"]))
    devices = sorted({e["device"] for e in entries})
    return {"_comment": COMMENT, "devices": devices,
            "directions": list(DIRECTIONS), "entries": entries}


def as_text(register):
    """The register as it is written: two-space JSON with a trailing newline.

    One entry per line, because a register is read in a diff as often as in a
    browser and `indent=2` would put every field on its own line -- a
    five-field change per moved address.
    """
    lines = [json.dumps(item, sort_keys=True) for item in register["entries"]]
    head = {key: value for key, value in register.items() if key != "entries"}
    body = ",\n    ".join(lines)
    return (json.dumps(head, indent=2)[:-2] + ",\n"
            + '  "entries": [\n    ' + body + "\n  ]\n}\n")


def main(argv):
    root = Path(__file__).resolve().parents[1]
    sys.path.insert(0, str(root / f"{PACKAGE}/home/aaa/.local/lib"))
    import a3_osc

    register = build(a3_osc.load(root / TRUTH))
    target = root / REGISTER
    target.write_text(as_text(register))
    print(f"{len(register['entries'])} addresses -> {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
